
 
 fleets["British"] = {}

 fleets["British"]["1stRate"] = {
   name = "British 1stRate",
   url = "http://cloud-3.steamusercontent.com/ugc/1664601739753178843/380EDD042A4124BBC895C3383B92F7F91DEA9A5D/"
 }

 fleets["British"]["2thRate"] = {
   name = "British 2thRate",
   url = "http://cloud-3.steamusercontent.com/ugc/1664601739758009353/6E556E561D43B9FF9017DAC8AE47BDF58768DC78/"
 }

 fleets["British"]["3thRate"] = {
   name = "British 3thRate",
   url = "http://cloud-3.steamusercontent.com/ugc/1681493480957598880/F4204F51D8028FD94ABC5CB4EFCE57FE923B4BF6/"
 }

 fleets["British"]["4thRate"] = {
   name = "British 4thRate",
   url = "http://cloud-3.steamusercontent.com/ugc/1681493480957602529/9640CCEFDC91D6EED0EDE9EC91F750705C75481C/"
 }

 fleets["British"]["Frigate_5th_Rate"] = {
  name = "British Frigate 5th Rate",
  url = "http://cloud-3.steamusercontent.com/ugc/1681493865327727446/1044C87A870B55753E4D50B303F9BB0740464EF5/"
}

fleets["British"]["Brig"] = {
  name = "British Brig",
  url = "http://cloud-3.steamusercontent.com/ugc/1681493865327730222/0E3D3EC6D46D22D8ED9CCB5613BA6C5B88CBE255/"
}

